### ISSUE TITLE
crash on isReadableOrWritable

### ISSUE THREAD

**Issue by shinma** [IBM-Swift/BlueSocket#123] opened 2018-02-22 08:26 UTC
I'm struggling with one crash since version 0.12.87 (so I'm stuck on 0.12.86 which works fine). It happens almost every time when I start application and in-between running. I was hoping to see fix in each version but it did happen so I'm writing this issue. It always happens when I try to execute **isReadableOrWritable**. Please take a look at the code below.

_Device: any iPhone 64-bit
iOS: 10 or higher
Xcode: 9.2 (9C40b)_

        guard !socket.isConnected else {
            throw CommunicationError.connectionError
        }
        
        do {
            try socket.connect(to: hostName, port: port)
        } catch {
            throw CommunicationError.connectionError
        }
        
        do {
            try socket.setReadTimeout(value: 20000)
        } catch {
            throw CommunicationError.connectionError
        }
        
        do {
            try socket.setWriteTimeout(value: 4000)
        } catch {
            throw CommunicationError.connectionError
        }
        
        do {
            try socket.setBlocking(mode: true)
        } catch {
            throw CommunicationError.connectionError
        }
        
        //Write
        let dataSentCount = try socket.write(from: dataToSend)
        
        guard dataSentCount > 0 else {
            throw CommunicationError.socketWriteError
        }
        
        var isReadable = false
        
        //Read
        while !isReadable {
            do {
                let tuple = try socket.isReadableOrWritable(waitForever: false, timeout: 10)
                
                if tuple.readable {
                    break
                }
                
                isReadable = tuple.readable
            } catch {
                throw CommunicationError.socketReadError
            }
            
            Thread.sleep(forTimeInterval: 0.5)
        }

![zrzut ekranu 2018-02-22 o 09 22 19](https://user-images.githubusercontent.com/2297462/36527592-9ba44206-17b2-11e8-9a9f-7ebe31c4e88c.jpg)

![zrzut ekranu 2018-02-22 o 10 14 59](https://user-images.githubusercontent.com/2297462/36529661-498c0038-17b9-11e8-8111-f3720441664c.png)

I have used Debug version to pinpoint line causing error.

**Comment by billabt** [comment] 2018-02-22 18:50
I suspect that this problem and also the problem being seen in issue #125 is related to changes made in PR #110 and it's related PRs.  I never saw any of these problems prior to accepting that PR.

@AlanQuatermain:  Any ideas what could be causing this?  With the rash of bugs that have arisen since accepting this PR, _I'm considering rolling it back again_.

**Comment by AlanQuatermain** [comment] 2018-02-22 18:52
I’m not sure. We have unit tests covering these code paths don’t we? If we can reproduce the issue I ought to be able to resolve everything fairly quickly.

**Comment by billabt** [comment] 2018-02-22 19:08
The unit tests are covering _most_ of these code paths but probably not to the extent that it could catch these problems.  They seem to edge cases.

Take a look at issue #120.  This one is very similar to this case and the user reporting it provided code you can use in a _playground_.  Maybe trying that will give you a clue.  I'm still recovering from surgery and unfortunately can't sit (don't ask, 🤪) too long at the computer or I would've tried it before now.

**Comment by billabt** [comment] 2018-02-23 14:06
Fixed in _0.12.93_.

**Closed by billabt** 2018-02-23 14:06 UTC
