### ISSUE TITLE
Mem read 0x0 on 0.12.85

### ISSUE THREAD

**Issue by qhua948** [IBM-Swift/BlueSocket#110] opened 2018-01-21 22:50 UTC
Hi,

When I do a `isReadableOrWritable()` with a default TCP socket creation, I get a `error: memory read failed for 0x0`.

I can confirm this issue does not exist in 0.12.82.

**Comment by billabt** [comment] 2018-01-22 14:35
@AlanQuatermain:  Any chance you can take a look at this?  I'm a bit under the weather today...  It seems to be in the area related to the PR from you I just merged.  Thanks.

**Comment by billabt** [comment] 2018-01-22 15:00
@AlanQuatermain:  I did take a look at it a bit.  I looks like the problem is with fd_set.zero().  When that function is called, _self_ gets clobbered...

**Comment by billabt** [comment] 2018-01-22 15:08
@AlanQuatermain: If we can't get it fixed soon, I'll have to back out the FD changes temporarily...  This is going to break a few folks.

**Comment by billabt** [comment] 2018-01-22 15:39
The crash bug is now fixed in 0.12.86.  Let me know if you have any problems.  Thanks.

**Closed by billabt** 2018-01-22 15:39 UTC

**Comment by AlanQuatermain** [comment] 2018-01-26 23:02
Eep; I'll take a look at this and see what I can figure out. I;'m laid up with a broken ankle right now, so I have plenty of time on my hands.

**Comment by AlanQuatermain** [comment] 2018-01-26 23:17
At a guess, I think maybe I'm using the UnsafeMutablePointer.initialize(to:count:) method incorrectly. Maybe that's changing the pointer value instead of the contents of the referenced memory? Once Xcode 9.3 finishes installing I'll run it through a debugger a few times to see what actual effect that has (grumbles something about the slowest company-owned laptop he's seen in twenty years…)

**Comment by AlanQuatermain** [comment] 2018-01-26 23:20
…or not, since it apparently requires High Sierra and I'm not allowed to install that on my company laptop. Le sigh.

**Comment by billabt** [comment] 2018-01-26 23:26
Sorry to hear about the ankle. I just found out I need some surgery, not sure when but soon. I’ll find out Tuesday. Anyway, if I don’t respond real quick, you’ll know why. 🤪

**Comment by AlanQuatermain** [comment] 2018-01-26 23:27
Ooof. Getting old sucks, doesn't it…? 😕

**Comment by billabt** [comment] 2018-01-26 23:28
For sure!!! 😖

**Comment by AlanQuatermain** [comment] 2018-01-27 00:02
The calls seem just fine. The actual fd_set doesn't seem to be problematic. I suspect what's actually happening is that the zero() call is clobbering the return address on the stack.

**Comment by AlanQuatermain** [comment] 2018-01-27 00:09
Oops, yeah, found it. I'm setting `__fd_set_size` on macOS to be `__DARWIN_FD_SET_SIZE / MemoryLayout<Int32>.stride`, i.e. set-size-in-bits / number of bytes in an Int32. That last bit should be number of *bits* in an Int32. Oops. So `zero()` on macOS was blanking 256 bytes of memory, not 32 bytes. Sigh. Nice small fix, though.

**Comment by billabt** [comment] 2018-01-27 00:30
Cool. I added a new test for the function that was failing, assuming that passes now, go ahead and redo the PR. Then we can get it merged again. Thanks. 

P.S. Take care of that ankle.
